// Parity test for the TS lexer port. Reads fixtures generated by
//   go test ./chassis/txcl/lexer/... -run TestGenerateFixtures -update
// from chassis/txcl/lexer/fixtures_test.go and asserts that the TS
// lexer produces the exact same (type, literal) sequence. When the
// Go grammar evolves, regenerate fixtures and the diff catches drift.

import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { lexAll } from './lexer'

interface FixtureToken {
    type: string
    literal: string
}
interface Fixture {
    name: string
    input: string
    tokens: FixtureToken[]
}

const fixturesDir = join(dirname(fileURLToPath(import.meta.url)), '__fixtures__')

function loadFixture(name: string): Fixture {
    const raw = readFileSync(join(fixturesDir, name + '.json'), 'utf8')
    return JSON.parse(raw) as Fixture
}

const index = JSON.parse(
    readFileSync(join(fixturesDir, 'index.json'), 'utf8'),
) as string[]

describe('TXCL lexer (parity with Go)', () => {
    for (const file of index) {
        const name = file.replace(/\.json$/, '')
        it(name, () => {
            const fx = loadFixture(name)
            const got = lexAll(fx.input).map((t) => ({
                type: t.type as string,
                literal: t.literal,
            }))
            expect(got).toEqual(fx.tokens)
        })
    }
})
