// TXCL lexer — direct port of chassis/txcl/lexer/lexer.go. The token
// stream (type + literal) is byte-for-byte identical to the Go lexer
// for ASCII inputs; parity is enforced by lexer.test.ts against JSON
// fixtures generated by `go test ./chassis/txcl/lexer/... -run
// TestGenerateFixtures -update`.
//
// Operates on a JavaScript string with charCodeAt. TXCL is ASCII-
// dominant (verbs, operators, path identifiers) so UTF-16 code units
// match byte semantics for everything the lexer pattern-matches on;
// non-ASCII characters only appear inside string literals where the
// lexer copies them through untouched.

import { TokenType, type Token, lookupIdent } from './tokens'

export class Lexer {
    private input: string
    private position = 0 // current position in input (points to current char)
    private readPosition = 0 // next reading position
    private ch = 0 // current charCode under examination; 0 = EOF
    private lastToken: Token = { type: TokenType.EOF, literal: '', start: 0, end: 0 }

    constructor(input: string) {
        this.input = input
        this.readChar()
    }

    nextToken(): Token {
        this.skipWhitespace()

        // Single-line comments. `# ... \n` are stripped before token
        // emission — same as the Go lexer.
        if (this.ch === CH_HASH) {
            this.skipComment()
            return this.nextToken()
        }

        const start = this.position

        let tok: Token

        switch (this.ch) {
            case CH_EQ:
                if (this.peekChar() === CH_EQ) {
                    this.readChar()
                    tok = { type: TokenType.EQ, literal: '==', start, end: this.position + 1 }
                } else if (this.peekChar() === CH_TILDE) {
                    this.readChar()
                    tok = { type: TokenType.MATCH, literal: '=~', start, end: this.position + 1 }
                } else {
                    tok = { type: TokenType.ASSIGN, literal: '=', start, end: start + 1 }
                }
                break
            case CH_PLUS:
                tok = { type: TokenType.PLUS, literal: '+', start, end: start + 1 }
                break
            case CH_MINUS:
                if (!isDigit(this.peekChar())) {
                    tok = { type: TokenType.MINUS, literal: '-', start, end: start + 1 }
                } else {
                    const literal = this.readNumber()
                    tok = {
                        type: literal.includes('.') ? TokenType.FLOAT : TokenType.INT,
                        literal,
                        start,
                        end: this.position,
                    }
                    this.lastToken = tok
                    return tok
                }
                break
            case CH_BANG:
                if (this.peekChar() === CH_EQ) {
                    this.readChar()
                    tok = { type: TokenType.NOT_EQ, literal: '!=', start, end: this.position + 1 }
                } else if (this.peekChar() === CH_TILDE) {
                    this.readChar()
                    tok = { type: TokenType.NO_MATCH, literal: '!~', start, end: this.position + 1 }
                } else {
                    tok = { type: TokenType.BANG, literal: '!', start, end: start + 1 }
                }
                break
            case CH_SLASH:
                if (isBinding(this.lastToken.type)) {
                    const literal = this.readRegex()
                    tok = { type: TokenType.REGEX, literal, start, end: this.position + 1 }
                } else {
                    tok = { type: TokenType.SLASH, literal: '/', start, end: start + 1 }
                }
                break
            case CH_STAR:
                tok =
                    this.lastToken.type === TokenType.WHEN
                        ? { type: TokenType.STAR, literal: '*', start, end: start + 1 }
                        : { type: TokenType.ASTERISK, literal: '*', start, end: start + 1 }
                break
            case CH_LT:
                if (this.peekChar() === CH_EQ) {
                    this.readChar()
                    tok = { type: TokenType.LT_EQ, literal: '<=', start, end: this.position + 1 }
                } else {
                    tok = { type: TokenType.LT, literal: '<', start, end: start + 1 }
                }
                break
            case CH_GT:
                if (this.peekChar() === CH_EQ) {
                    this.readChar()
                    tok = { type: TokenType.GT_EQ, literal: '>=', start, end: this.position + 1 }
                } else {
                    tok = { type: TokenType.GT, literal: '>', start, end: start + 1 }
                }
                break
            case CH_SEMI:
                tok = { type: TokenType.SEMICOLON, literal: ';', start, end: start + 1 }
                break
            case CH_COLON:
                tok = { type: TokenType.COLON, literal: ':', start, end: start + 1 }
                break
            case CH_COMMA:
                tok = { type: TokenType.COMMA, literal: ',', start, end: start + 1 }
                break
            case CH_DOT:
                if (isLetter(this.peekChar())) {
                    const literal = this.readBranchString()
                    tok = { type: TokenType.BRANCH, literal, start, end: this.position + 1 }
                } else {
                    // Mirrors Go's `case '.':` with no else — produces an
                    // empty-typed token that the parser ignores. Real
                    // TXCL never emits a bare `.` so this is unreachable
                    // in practice; preserved for byte-parity with Go.
                    tok = { type: '' as TokenType, literal: '', start, end: start + 1 }
                }
                break
            case CH_AT:
                if (isLetter(this.peekChar())) {
                    const literal = this.readAtBranchString()
                    tok = { type: TokenType.BRANCH, literal, start, end: this.position + 1 }
                } else {
                    tok = { type: TokenType.ILLEGAL, literal: '@', start, end: start + 1 }
                }
                break
            case CH_LBRACE:
                tok = { type: TokenType.LBRACE, literal: '{', start, end: start + 1 }
                break
            case CH_RBRACE:
                tok = { type: TokenType.RBRACE, literal: '}', start, end: start + 1 }
                break
            case CH_LPAREN:
                tok = { type: TokenType.LPAREN, literal: '(', start, end: start + 1 }
                break
            case CH_RPAREN:
                tok = { type: TokenType.RPAREN, literal: ')', start, end: start + 1 }
                break
            case CH_QUOTE: {
                const literal = this.readString()
                tok = { type: TokenType.STRING, literal, start, end: this.position + 1 }
                break
            }
            case CH_LBRACK:
                tok = { type: TokenType.LBRACKET, literal: '[', start, end: start + 1 }
                break
            case CH_RBRACK:
                tok = { type: TokenType.RBRACKET, literal: ']', start, end: start + 1 }
                break
            case CH_AMP:
                if (this.peekChar() === CH_AMP) {
                    this.readChar()
                    tok = { type: TokenType.LAND, literal: '&&', start, end: this.position + 1 }
                } else if (isLetter(this.peekChar())) {
                    // `&fn` function-call sigil. Step off the `&` onto
                    // the first ident byte, read the identifier, return
                    // early — readIdentifier already advanced past the
                    // last ident byte (mirrors lexer.go:172-188).
                    this.readChar()
                    const literal = this.readIdentifier()
                    tok = { type: TokenType.AMP_IDENT, literal, start, end: this.position }
                    this.lastToken = tok
                    return tok
                } else {
                    tok = { type: TokenType.ILLEGAL, literal: '&', start, end: start + 1 }
                }
                break
            case CH_PIPE:
                if (this.peekChar() === CH_PIPE) {
                    this.readChar()
                    tok = { type: TokenType.LOR, literal: '||', start, end: this.position + 1 }
                } else {
                    tok = { type: TokenType.ILLEGAL, literal: '|', start, end: start + 1 }
                }
                break
            case 0:
                tok = { type: TokenType.EOF, literal: '', start, end: start }
                break
            default:
                if (isLetter(this.ch)) {
                    const literal = this.readIdentifier()
                    // `b64"..."` is a typed-string prefix: the lexer
                    // consumes the identifier, then if the very next
                    // byte is `"` it reads a string and emits it as
                    // STRING with the literal replaced by the base64
                    // encoding of the raw bytes.
                    if (literal === 'b64' && (this.ch as number) === CH_QUOTE) {
                        const raw = this.readString()
                        tok = {
                            type: TokenType.STRING,
                            literal: base64Encode(raw),
                            start,
                            end: this.position + 1,
                        }
                        this.readChar()
                        this.lastToken = tok
                        return tok
                    }
                    tok = {
                        type: lookupIdent(literal),
                        literal,
                        start,
                        end: this.position,
                    }
                    this.lastToken = tok
                    return tok
                } else if (isDigit(this.ch)) {
                    const literal = this.readNumber()
                    tok = {
                        type: literal.includes('.') ? TokenType.FLOAT : TokenType.INT,
                        literal,
                        start,
                        end: this.position,
                    }
                    this.lastToken = tok
                    return tok
                } else {
                    tok = {
                        type: TokenType.ILLEGAL,
                        literal: String.fromCharCode(this.ch),
                        start,
                        end: start + 1,
                    }
                }
        }

        this.readChar()
        this.lastToken = tok
        return tok
    }

    private skipWhitespace(): void {
        while (
            this.ch === CH_SPACE ||
            this.ch === CH_TAB ||
            this.ch === CH_LF ||
            this.ch === CH_CR
        ) {
            this.readChar()
        }
    }

    private skipComment(): void {
        while (this.ch !== CH_LF && this.ch !== 0) {
            this.readChar()
        }
        this.skipWhitespace()
    }

    private readChar(): void {
        this.ch = this.readPosition >= this.input.length ? 0 : this.input.charCodeAt(this.readPosition)
        this.position = this.readPosition
        this.readPosition += 1
    }

    private peekChar(): number {
        return this.readPosition >= this.input.length ? 0 : this.input.charCodeAt(this.readPosition)
    }

    private readIdentifier(): string {
        const start = this.position
        while (isLetter(this.ch) || (this.ch >= CH_0 && this.ch <= CH_9)) {
            this.readChar()
        }
        return this.input.slice(start, this.position)
    }

    private readNumber(): string {
        const start = this.position
        while (isDigit(this.ch)) {
            this.readChar()
        }
        return this.input.slice(start, this.position)
    }

    // `.`-led branch. Caller has verified peekChar() is a letter.
    // Returns the assembled branch string including the leading `.`,
    // with quoted segments unescaped + gjson metachars `\`-prefixed.
    private readBranchString(): string {
        let out = String.fromCharCode(this.ch) // leading `.`
        this.readChar() // step onto first identifier byte
        out += this.scanBranchRun()
        return out
    }

    // `@foo.bar` → `._txc.foo.bar`. The lexer rewrites @ sugar so the
    // parser sees a regular branch into the request envelope.
    private readAtBranchString(): string {
        let out = '._txc.'
        this.readChar() // step off `@` onto first identifier byte
        out += this.scanBranchRun()
        return out
    }

    private scanBranchRun(): string {
        let out = String.fromCharCode(this.ch)
        for (;;) {
            const next = this.peekChar()
            if (next === CH_QUOTE) {
                this.readChar() // onto opening quote
                out += this.appendQuotedSegment()
                continue
            }
            if (!isBranchChar(next)) {
                break
            }
            this.readChar()
            out += String.fromCharCode(this.ch)
        }
        return out
    }

    // Quoted segment inside a branch path. gjson/sjson treats `. * ? \`
    // as path metacharacters, so a key like "content-type" stays one
    // segment by escaping. Caller positions us on the opening `"`; on
    // return this.ch is the closing `"` (or 0 if unterminated).
    private appendQuotedSegment(): string {
        let out = ''
        for (;;) {
            this.readChar()
            if (this.ch === 0 || this.ch === CH_QUOTE) break
            if (
                this.ch === CH_BACKSLASH ||
                this.ch === CH_DOT ||
                this.ch === CH_STAR ||
                this.ch === CH_QUESTION
            ) {
                out += '\\' + String.fromCharCode(this.ch)
            } else {
                out += String.fromCharCode(this.ch)
            }
        }
        return out
    }

    private readRegex(): string {
        // Caller is on the opening `/`. Go captures `position+1` (one
        // past the opening slash) then advances, copying body bytes,
        // skipping `\/` escapes, until the next bare `/`. We mirror.
        const start = this.position + 1
        while (this.ch !== 0) {
            this.readChar()
            if ((this.ch as number) === CH_BACKSLASH && this.peekChar() === CH_SLASH) {
                this.readChar()
                this.readChar()
            }
            if ((this.ch as number) === CH_SLASH) break
        }
        return this.input.slice(start, this.position).replace(/\\\//g, '/')
    }

    private readString(): string {
        let out = ''
        for (;;) {
            this.readChar()
            if (this.ch === 0 || this.ch === CH_QUOTE) break
            if (this.ch === CH_BACKSLASH) {
                this.readChar()
                switch (this.ch as number) {
                    case CH_QUOTE:
                        out += '"'
                        break
                    case CH_BACKSLASH:
                        out += '\\'
                        break
                    case CH_N_LOWER:
                        out += '\n'
                        break
                    case CH_R_LOWER:
                        out += '\r'
                        break
                    case CH_T_LOWER:
                        out += '\t'
                        break
                    case 0:
                        return out
                    default:
                        // Unknown escape — preserve both bytes verbatim so
                        // authors don't lose content. Same posture as Go.
                        out += '\\' + String.fromCharCode(this.ch)
                }
                continue
            }
            out += String.fromCharCode(this.ch)
        }
        return out
    }
}

// Drive the lexer to EOF (inclusive) and return the token stream.
// Convenience wrapper used by both the parity test and downstream
// consumers (CodeMirror StreamLanguage, etc.).
export function lexAll(input: string): Token[] {
    const lx = new Lexer(input)
    const out: Token[] = []
    for (;;) {
        const t = lx.nextToken()
        out.push(t)
        if (t.type === TokenType.EOF) break
    }
    return out
}

// ──────────────────────────────────────────────────────────────────
// helpers (mirror chassis/txcl/lexer/lexer.go: isLetter, isDigit,
// isBranchChar, isBinding)

function isLetter(ch: number): boolean {
    return (
        (ch >= CH_A_LOWER && ch <= CH_Z_LOWER) ||
        (ch >= CH_A_UPPER && ch <= CH_Z_UPPER) ||
        ch === CH_UNDER
    )
}

function isDigit(ch: number): boolean {
    // Go's isDigit also accepts `.` and `-` so a single readNumber call
    // can pick up `1.5` and (when peeked-into via the `-` switch arm)
    // negative-led numbers.
    return (ch >= CH_0 && ch <= CH_9) || ch === CH_DOT || ch === CH_MINUS
}

function isBranchChar(ch: number): boolean {
    // `-` allowed mid-run so hyphenated keys (content-type, x-request-id)
    // are addressable without quoting.
    return isLetter(ch) || (ch >= CH_0 && ch <= CH_9) || ch === CH_DOT || ch === CH_MINUS
}

function isBinding(t: TokenType): boolean {
    return t === TokenType.MATCH || t === TokenType.NO_MATCH
}

// Encodes a raw string's UTF-8 bytes as standard base64 — matches Go's
// `base64.StdEncoding.EncodeToString([]byte(raw))` for ASCII inputs,
// which is the only thing TXCL fixtures exercise. `btoa` is available
// in browsers and Node ≥16.
function base64Encode(raw: string): string {
    return btoa(raw)
}

// ──────────────────────────────────────────────────────────────────
// charcode constants — keeps the switch table readable.

const CH_TAB = 9
const CH_LF = 10
const CH_CR = 13
const CH_SPACE = 32
const CH_BANG = 33
const CH_QUOTE = 34
const CH_HASH = 35
const CH_AMP = 38
const CH_LPAREN = 40
const CH_RPAREN = 41
const CH_STAR = 42
const CH_PLUS = 43
const CH_COMMA = 44
const CH_MINUS = 45
const CH_DOT = 46
const CH_SLASH = 47
const CH_0 = 48
const CH_9 = 57
const CH_COLON = 58
const CH_SEMI = 59
const CH_LT = 60
const CH_EQ = 61
const CH_GT = 62
const CH_QUESTION = 63
const CH_AT = 64
const CH_A_UPPER = 65
const CH_Z_UPPER = 90
const CH_LBRACK = 91
const CH_BACKSLASH = 92
const CH_RBRACK = 93
const CH_UNDER = 95
const CH_A_LOWER = 97
const CH_N_LOWER = 110
const CH_R_LOWER = 114
const CH_T_LOWER = 116
const CH_Z_LOWER = 122
const CH_LBRACE = 123
const CH_PIPE = 124
const CH_RBRACE = 125
const CH_TILDE = 126
