package cli

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/pflag"

	"github.com/loremlabs/thanks-computer/chassis/cli/banner"
	"github.com/loremlabs/thanks-computer/chassis/cli/template"
)

// stubTxcl is the resonator.txcl scaffold written by `txco init` when no
// --from source is given. Self-contained by design: a bare EMIT writes a
// field into the envelope and needs no external service, so `txco apply`
// then a request shows something working immediately. (The old default
// EXEC'd http://localhost:9000/echo, which silently did nothing unless
// the user happened to be running an echo server.)
const stubTxcl = `# generated by txco init — replace this with your rule logic.
EMIT .hi = "hello"
`

// runInit scaffolds a local OPS/<stack>/ tree.
//
//	txco init <stack-name> [<dir>]                                   # local stub
//	txco init <stack-name> [<dir>] --from github:owner/repo[/path]   # from template
//
// dir defaults to cwd. <stack-name> may contain slashes (e.g. website/canary).
func runInit(args []string, stdout, stderr io.Writer) int {
	// pflag (vs. stdlib flag) is used here so flags and positional args can
	// be interleaved — e.g. `txco init support --from github:...` works the
	// same as `txco init --from github:... support`.
	fs := pflag.NewFlagSet("init", pflag.ContinueOnError)
	fs.SetOutput(stderr)
	scope := fs.Int("scope", 100, "initial scope number for the stub rule (ignored when --from is set)")
	from := fs.String("from", "", "fetch a starter tree from a remote source (e.g. github:owner/repo[@ref][/subpath])")
	fs.Usage = func() {
		banner.PrintLogo(stderr)
		fmt.Fprint(stderr, `
Usage: txco init <stack-name> [<dir>] [flags]

Scaffold a local OPS/<stack>/ tree. By default, writes a single stub
resonator.txcl at scope 100. With --from <source>, downloads a template
tree and copies its contents directly under OPS/<stack>/.

Source spec (v1):
  github:owner/repo                       # default branch (main, then master)
  github:owner/repo@ref                   # specific branch / tag / commit
  github:owner/repo/sub/path              # subdirectory
  github:owner/repo@ref/sub/path          # both

Flags:
`)
		fs.PrintDefaults()
	}
	if err := fs.Parse(args); err != nil {
		return 2
	}

	if fs.NArg() < 1 {
		fs.Usage()
		return 2
	}
	stack := strings.Trim(fs.Arg(0), "/")
	if stack == "" {
		fmt.Fprintln(stderr, "init: stack name cannot be empty")
		return 2
	}

	dir, err := resolveDir(fs.Arg(1))
	if err != nil {
		fmt.Fprintf(stderr, "init: resolve dir: %v\n", err)
		return 1
	}

	stackDir := filepath.Join(dir, "OPS", stack)
	if err := ensureEmptyOrCreate(stackDir); err != nil {
		fmt.Fprintf(stderr, "init: %v\n", err)
		return 1
	}

	if *from != "" {
		fmt.Fprintf(stdout, "fetching %s ...\n", *from)
		n, err := template.Fetch(context.Background(), *from, stackDir)
		if err != nil {
			fmt.Fprintf(stderr, "init: fetch %s: %v\n", *from, err)
			return 1
		}
		if n == 0 {
			fmt.Fprintf(stderr, "init: %s yielded 0 files (subpath wrong, or empty subtree)\n", *from)
			return 1
		}
		fmt.Fprintf(stdout, "fetched %d file(s) into %s\n", n, stackDir)
		fmt.Fprintln(stdout, "review the files, then run `txco apply` to push to a chassis.")
		return 0
	}

	leaf := filepath.Join(stackDir, fmt.Sprintf("%d", *scope))
	if err := os.MkdirAll(leaf, 0o755); err != nil {
		fmt.Fprintf(stderr, "init: mkdir %s: %v\n", leaf, err)
		return 1
	}
	target := filepath.Join(leaf, "resonator.txcl")
	if err := os.WriteFile(target, []byte(stubTxcl), 0o644); err != nil {
		fmt.Fprintf(stderr, "init: write %s: %v\n", target, err)
		return 1
	}
	fmt.Fprintf(stdout, "scaffolded %s\n", target)
	fmt.Fprintln(stdout, "edit the file, then run `txco apply` to push it to a chassis")
	fmt.Fprintln(stdout, "(`txco apply` finds OPS/ at or above the current dir — run it from anywhere in this tree).")
	return 0
}

// ensureEmptyOrCreate makes p (and parents) when missing, but errors if p
// exists with any non-hidden contents — we don't want to silently merge a
// template into a populated stack directory.
func ensureEmptyOrCreate(p string) error {
	info, err := os.Stat(p)
	if os.IsNotExist(err) {
		return os.MkdirAll(p, 0o755)
	}
	if err != nil {
		return err
	}
	if !info.IsDir() {
		return fmt.Errorf("%s exists and is not a directory", p)
	}
	entries, err := os.ReadDir(p)
	if err != nil {
		return err
	}
	for _, e := range entries {
		if !strings.HasPrefix(e.Name(), ".") {
			return fmt.Errorf("%s already contains %s; not overwriting", p, e.Name())
		}
	}
	return nil
}
